# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Only if your site type is GitHub Project sites and doesn't have a custom domain,
# change below value to '/projectname'.
baseurl: ''

# The language of the site layout › http://www.lingoes.net/en/translator/langcode.htm
# Go to folder '_data/locales' to check the available language options
lang: en

# The lang attribute of HTML › http://www.lingoes.net/en/translator/langcode.htm
# We can specify a language different from the layout of the content.
# If it is not assigned, the site will use the value of 'lang' instead.
content_lang: ''

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Europe/London

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: A Pentesters Ramblings                          # the main title

tagline: Notes, Tools, WriteUps and Walkthroughs       # it will display as the sub-title

description: >-                        # used by seo meta and the atom feed
  A way to recall methodologies,
  during engagements when a
  specific challenge or cirumstance
  presents itself.

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: 'https://sp00ks-git.github.io'

github:
  username: sp00ks-git             # change to your github username

twitter:
  username: __sp00ks__            # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: sp00ks
  email: sp00ks_secure@protonmail.com       # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/__sp00ks__      # change to your twitter homepage
    - https://github.com/sp00ks-git       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification: G-D6YBGPQR7B # change to your verification string

# ↑ --------------------------


google_analytics:
  id: 'G-D6YBGPQR7B'              # fill in your Google Analytics ID
  # Google Analytics pageviews report settings
  pv:
    proxy_endpoint:   # fill in the Google Analytics superProxy endpoint of Google App Engine
    cache_path:       # the local PV cache data, friendly to visitors from GFW region

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode: # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn: ''

# the avatar on sidebar, support local or CORS resources
avatar: https://pbs.twimg.com/profile_images/1193836408328392706/edj7waav_400x400.jpg

# boolean type, the global switch for ToC in posts.
toc: true

disqus:
  comments: false  # boolean type, the global switch for posts comments.
  shortname: ''    # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order


defaults:
  -
    scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: false    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true    # Hide title in mobile screens.

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - '*.json'

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# Outdated configuration warning
outdated: '-- Missing configuration options! --'
